mutation AddIncident($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Addexternalmanufacturingincident",
"payload":{
    "aptBusinessObjectSummary": "GraphQL test run 4/18/24",
    "aptBusinessObjectDescription":"Adding an incident programmatically from postman using graphQL walkthrough demo.",
    "externalManufacturingImpact":{
    "businessPriority":"MEDIUM"
    },
    "resolutionDueDate":1736613281000 // 11 Jan 2025
    }
}