query ListIncidentComments($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Listcommentsforincident",
"payload":{
    "id":"{{external_manufacturing_incident_id}}",
    "processType":"externalManufacturingIncident"
    }
}