mutation AddIncident($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Addincident",
"payload":{
    "aptBusinessObjectSummary": "GraphQL flow test run",
    "aptBusinessObjectDescription":"Adding an incident programmatically from postman using graphQL",
    "businessPriority":"MEDIUM",
    "incidentType":"LABEL_COMPLIANCE_ERROR",
    "resolutionDueDate":"1736613281000", // 11 Jan 2025
    "responsiblePartyAtParner":{}
    }
}