mutation AddIncidentComments($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Addcommentforincident",
"payload":{
    "processId":"{{incident_id}}",
    "processType":"incident",
        "aptCommentBox":{
      "aptComment":{
        "commentText": "Adding a test comment using Postman and GraphQL.",
        "visibilityType": "Public"
      }
    }
    }
}