mutation AddTaskTemplate($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Addtasktemplate",
"payload":{
    "templateName": "GQL Postman Created Task Template",
    "aptBusinessObjectDescription": "Template to demonstrate subTask creation via GraphQL API and Postman",
    "isTemplateModifiableByMember": true,
    "isAddRemoveSubtaskAllowed": true,
    "completionRequiredWithinDays": 14,
    "businessPriority": "LOW"
}
}