mutation EditDSIncident($action: String!, $payload: JSON!)
{
    genericActionCall(action: $action, payload: $payload)
    {
    result
    __typename
    }    
}

{
"action": "Editdirectsupplierincident",
"payload":{
    "id":"{{direct_supplier_incident_id}}",
    "aptBusinessObjectDescription":"Editing an incident programmatically using graphQL via Postman",
    "businessPriority":"LOW",
    "responsiblePartyAtParner":{}
    }
}