mutation AddCommentForTask($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Addcommentforprocess",
"payload":{
    "processId":"{{task_id}}",
    "processType": "task",
            "aptCommentBox":{
            "aptComment":{
                "commentText": "Adding a comment using GraphQL via Postman",
                "visibilityType": "Public"
            }
        }
    }
}