mutation CloseTask($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Closetask",
"payload":{
    "id":"{{task_id}}",
    "taskResolutionType":"CANCELLED"
    }
}