mutation EditCommentForTask($action: String!, $payload: JSON!) {
  genericActionCall(action: $action, payload: $payload) {
    result
    __typename
  }
}

{
"action": "Editcommentforprocess",
"payload":{
    "id":"{{task_comment_id}}",
    "processType": "task",
            "aptCommentBox":{
            "aptComment":{
                "commentText": "Modifying the comment programmatically using GraphQL via Postman",
                "visibilityType": "Public"
            }
        }
    }
}